Coordinate Research:
  agent: research_coordinator
  description: >
    Oversee the research process for {topic}.
    1. Assign tasks, define scope, and ensure the research direction aligns with the final crash course goal.
    2. Try to cover all relevant aspects of the topic.
  expected_output: >
    A clear research plan and outline for the {topic} crash course.

Conduct Technical Research:
  agent: researcher
  description: >
    Perform in-depth research on {topic} based on the outline. Create a comprehensive, structured document with examples, use cases, and real-world context.
  expected_output: >
    A detailed and well-structured draft crash course document covering all key areas of {topic}.

Validate Final Output:
  agent: validator
  description: >
    Review the draft document for factual accuracy, structure, and readability. Suggest improvements and ensure it meets quality standards for publishing.
  expected_output: >
    A final version of the crash course document that is accurate, clear, concise, and ready for consumption.
  output_file: output/report.md
